### ISSUE TITLE
Issues compiling under macOS

### ISSUE THREAD

**Issue by legraphista** [voixen/voixen-vad#7]
Hello!

I am looking forward to use this repo but i have some issues when installing it: `npm i git+https://github.com/voixen/voixen-vad.git`

I checked out #3 and tried all the steps provided, but nothing worked 
OS: macOS 10.13.3
xCode: 9.2 (9C40b)
node -v: v8.9.1
npm -v: 5.2.0
clang -v:
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
 ___

I tried cloning the repo and building from there but, i get the same error as i got while trying to install it.
Log:
```
$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@8.9.4 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/bitstream.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/dct64.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/decode.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/layer1.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/layer2.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/layer3.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/mpadec.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/mpadec_interface.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/tabinit.o
  CC(target) Release/obj.target/mpadec/vendor/mpadec/src/vbrtag.o
../vendor/mpadec/src/vbrtag.c:138:23: warning: comparison of array 'pTagData->toc' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (pTagData->toc != NULL) {
            ~~~~~~~~~~^~~    ~~~~
1 warning generated.
  LIBTOOL-STATIC Release/mpadec.a
  CXX(target) Release/obj.target/mpa/src/mpa_bindings.o
../src/mpa_bindings.cc:334:7: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
        Nan::ForceSet(target, Nan::New("MPA_INPUT_BUFFER_SIZE").ToLocalChecked(), Nan::New(4096),    // nicely align to page
             ^
../node_modules/nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../node_modules/nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/mpa_bindings.cc:336:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(target, Nan::New("MPA_SAMPLE_BUFFER_SIZE").ToLocalChecked(),
         ^
../node_modules/nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../node_modules/nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/mpa_bindings.cc:339:10: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
    Nan::ForceSet(target, Nan::New("MPA_FLOAT_BUFFER_SIZE").ToLocalChecked(),
         ^
../node_modules/nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../node_modules/nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings generated.
  SOLINK(target) Release/mpa.node
Undefined symbols for architecture x86_64:
  "v8::HandleScope::CreateHandle(v8::internal::HeapObject*, v8::internal::Object*)", referenced from:
      Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "v8::HandleScope::CreateHandle(v8::internal::Isolate*, v8::internal::Object*)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const in mpa_bindings.o
      Nan::AsyncWorker::GetFromPersistent(char const*) const in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
  "v8::HandleScope::HandleScope(v8::Isolate*)", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      ...
  "v8::HandleScope::~HandleScope()", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      ...
  "v8::HandleScope::~HandleScope()", referenced from:
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleOKCallback() in mpa_bindings.o
      Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const in mpa_bindings.o
      ...
  "v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::ObjectTemplate::SetInternalFieldCount(int)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::ObjectTemplate::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)", referenced from:
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
  "v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::EscapableHandleScope::Escape(v8::internal::Object**)", referenced from:
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleOKCallback() in mpa_bindings.o
      Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const in mpa_bindings.o
      ...
  "v8::EscapableHandleScope::EscapableHandleScope(v8::Isolate*)", referenced from:
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleOKCallback() in mpa_bindings.o
      Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const in mpa_bindings.o
      ...
  "v8::V8::ToLocalEmpty()", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      ...
  "v8::V8::DisposeGlobal(v8::internal::Object**)", referenced from:
      Nan::AsyncWorker::AsyncWorker(Nan::Callback*) in mpa_bindings.o
      Nan::AsyncWorker::WorkComplete() in mpa_bindings.o
      Nan::AsyncWorker::~AsyncWorker() in mpa_bindings.o
  "v8::V8::FromJustIsNothing()", referenced from:
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "v8::V8::GlobalizeReference(v8::internal::Isolate*, v8::internal::Object**)", referenced from:
      Nan::Callback::Callback(v8::Local<v8::Function> const&) in mpa_bindings.o
      Nan::AsyncWorker::AsyncWorker(Nan::Callback*) in mpa_bindings.o
  "v8::Object::SetInternalField(int, v8::Local<v8::Value>)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::Object::SlowGetInternalField(int)", referenced from:
      Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "v8::Object::Get(v8::Local<v8::Value>)", referenced from:
      Nan::AsyncWorker::GetFromPersistent(char const*) const in mpa_bindings.o
  "v8::Object::New(v8::Isolate*)", referenced from:
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      Nan::AsyncWorker::AsyncWorker(Nan::Callback*) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::HandleOKCallback() in mpa_bindings.o
  "v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)", referenced from:
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
  "v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)", referenced from:
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::HandleOKCallback() in mpa_bindings.o
  "v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)", referenced from:
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
  "v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int)", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
      ...
  "v8::Context::Global()", referenced from:
      mpa::DecodeFrameWorker<short>::HandleOKCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
      Nan::AsyncWorker::HandleOKCallback() in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::HandleOKCallback() in mpa_bindings.o
  "v8::Integer::New(v8::Isolate*, int)", referenced from:
      Nan::New(int) in mpa_bindings.o
  "v8::Isolate::GetCurrent()", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      ...
  "v8::Isolate::ThrowException(v8::Local<v8::Value>)", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
  "v8::Isolate::GetCurrentContext()", referenced from:
      mpa::GetFrameInfoObject(_mp3data_struct const&, int) in mpa_bindings.o
      mpa::init(v8::Local<v8::Object>) in mpa_bindings.o
      Nan::New(int) in mpa_bindings.o
      Nan::Export(v8::Local<v8::Object>, char const*, void (*)(Nan::FunctionCallbackInfo<v8::Value> const&)) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
      ...
  "v8::External::New(v8::Isolate*, void*)", referenced from:
      Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(Nan::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>) in mpa_bindings.o
  "v8::Exception::Error(v8::Local<v8::String>)", referenced from:
      Nan::AsyncWorker::HandleErrorCallback() in mpa_bindings.o
  "v8::Exception::TypeError(v8::Local<v8::String>)", referenced from:
      Nan::ThrowTypeError(char const*) in mpa_bindings.o
  "node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)", referenced from:
      Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const in mpa_bindings.o
  "node::Buffer::HasInstance(v8::Local<v8::Value>)", referenced from:
      mpa::initDecoder(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::freeDecoder(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "node::Buffer::Data(v8::Local<v8::Value>)", referenced from:
      mpa::initDecoder(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::freeDecoder(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      ...
  "node::Buffer::Length(v8::Local<v8::Value>)", referenced from:
      mpa::initDecoder(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::getLastFrameInfo(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      mpa::DecodeFrameWorker<short>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
      mpa::DecodeFrameWorker<float>::DecodeFrameWorker(Nan::Callback*, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::Local<v8::Value>, int) in mpa_bindings.o
  "v8::Value::Int32Value(v8::Local<v8::Context>) const", referenced from:
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "v8::Value::ToInt32(v8::Local<v8::Context>) const", referenced from:
      Nan::New(int) in mpa_bindings.o
  "v8::External::Value() const", referenced from:
      Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "_node_module_register", referenced from:
      _register_mpa() in mpa_bindings.o
  "_uv_default_loop", referenced from:
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
  "_uv_queue_work", referenced from:
      void mpa::decodeFrame<short>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
      void mpa::decodeFrame<float>(Nan::FunctionCallbackInfo<v8::Value> const&) in mpa_bindings.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/mpa.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/Stefan/.nvm/versions/node/v8.9.4/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/Stefan/Desktop/GitHub/voixen-vad
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

**Comment by PJanko** [comment]
Hello @legraphista, 

Do you find any solution to your issue ? I'm facing the same one.

Regards

**Comment by p9f** [comment]
https://github.com/Snirpo/node-vad/issues/2
